pipeline {
  agent {
    docker { label 'qtr' image 'rikorose/gcc-cmake:10' }
  }
  stages {
    stage('build') {
      steps {
        sh 'mkdir build && cd build'
        sh 'cmake ..'
        sh 'cmake --build .'
      }
    }
    stage('test') {
      steps {
        sh './bin/tests'
      }
    }
  }
}
